name: conda

on:
  workflow_dispatch:
  push:
     branches:
       - main-

jobs:
  build:
    runs-on: macos-15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12.9
          channels: conda-forge
      - name: build-conda
        run: |
          env
          export CMAKE_PREFIX_PATH=$CONDA_PREFIX
          cd omni
          conda install -y conda-build
          conda install -y conda-verify
          conda install -y anaconda-client
          conda-build .
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: omni-0.0.0-py312_0.tar.bz2
          path: /Users/runner/miniconda3/envs/test/conda-bld/osx-arm64/omni-0.0.0-hcb8d3e5_0.conda

      - name: release
        run: |
          anaconda -t  "${{ secrets.ANACONDA_TOKEN }}" upload  /Users/runner/miniconda3/envs/test/conda-bld/osx-arm64/omni-0.0.0-hcb8d3e5_0.conda
