name: mac-13 conda

on:
  workflow_dispatch:
  push:
     branches:
       - main-

jobs:
  build:
    runs-on: macos-13
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12.9
          channels: conda-forge
      - name: build-conda
        run: |
          export CMAKE_PREFIX_PATH=$CONDA_PREFIX
          export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
          env
          cd omni
          conda install -y conda-build
          conda install -y conda-verify
          conda install -y anaconda-client
          conda-build .
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: omni-0.0.0-py312_0.tar.bz2
          path: /Users/runner/miniconda3/envs/test/conda-bld/osx-64/omni-0.0.0-ha5a8b8e_0.conda

      - name: release
        run: |
          anaconda -t  "${{ secrets.ANACONDA_TOKEN }}" upload /Users/runner/miniconda3/envs/test/conda-bld/osx-64/omni-0.0.0-ha5a8b8e_0.conda
