name: r

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86_64
            version: '7.8'
            host: ubuntu-latest
            site: obsd-7.8
          - name: openbsd
            architecture: arm64
            version: '7.8'
            host: ubuntu-latest
            site: obsd-7.8.arm64
    steps:
      - name: checkout wrp
        uses: actions/checkout@v6

      - name: checkout omni
        uses: actions/checkout@v6
        with:
          repository: hyoklee/omni
          path: omni

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add cmake poco yaml-cpp
            mkdir omni/build
            cd omni/build
            cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/omni/install
            make && make install
            cd ../..
            mkdir build
            cd build
            cmake -Domni_DIR=$HOME/omni/install/lib/cmake/omni \
                  -DSITE="${{ matrix.os.name }}-${{ matrix.os.version }}.${{ matrix.os.architecture}}" -DBUILDNAME="wrp" ..
            ctest -C Release -D Experimental
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
