name: r

on:
  push:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os.name }} ${{ matrix.os.architecture }} ${{ matrix.os.version }} on ${{ matrix.os.host }}
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: openbsd
            architecture: x86_64
            version: '7.8'
            host: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: ${{ matrix.os.name }}
        uses: cross-platform-actions/action@master
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: '${{ matrix.os.version }}'
          shell: bash
          run: |
            sudo pkg_add cmake yaml-cpp zeromq
            mkdir build
            cd build
            cmake -DSITE="obsd-7.8" -DBUILDNAME="omni/r" ..
            ctest -C Release -D Experimental
           cd ..
            mkdir poco
            cd poco
            cmake -DPOCO=ON -DSITE="obsd-7.8" -DBUILDNAME="omni/r/poco" ..
            ctest -C Release -D Experimental
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
