name: win omni r

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2025]        
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: |
          vcpkg install poco[crypto,netssl] yaml-cpp
          vcpkg integrate install
      - name: test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r" ..
          ctest -C Release -D Experimental
          cd ..
        shell: cmd
      - name: poco
        run: |
          mkdir poco
          cd poco
          cmake -DPOCO=ON -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DSITE:STRING="${{ matrix.os }}" -DBUILDNAME="omni/r/poco" ..
          ctest -C Release -D Experimental
        shell: cmd
